### ISSUE TITLE
What's the best way to check whether a commit exists?

### ISSUE THREAD

**Issue by justincy** [trepo/trepo-js#3]
Given a commit ID, how can I check whether it exists? The only thing I could find is to query `/graph/log` for all commits and compare IDs. It would be handy to have an endpoint that retrieved a given commit or  told me whether it existed.

I need this for syncing. If the remote and local are out of sync, I need to know whether the remote's latest commit exists locally.

**Comment by jonnymbgood** [comment]
Ok. This will need to be supported in vGraph and in the trepo api spec. Issues listed below:
API spec: https://github.com/trepo/api/issues/2
vGraph spec: https://github.com/trepo/vgraph/issues/8
vgraph-js: https://github.com/trepo/vgraph-js/issues/2

**Comment by jonnymbgood** [comment]
Will be addressed by #6 and #7
